#!/usr/bin/env node
/**
 * Install the native messaging host manifest for Chrome (design docs/05 §4).
 *
 * Chrome only launches a native host whose manifest lives in a fixed directory
 * and whose `allowed_origins` names the exact extension id (wildcards are
 * rejected). The extension id is derived from the pinned public key in
 * `extension/manifest.json`, so a re-install never changes it.
 *
 * Usage: node native-host/install.mjs [--print] [--uninstall]
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, chmodSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const HOST_NAME = 'com.dsh.web_companion'
const MANIFEST_DIR = join(homedir(), 'Library', 'Application Support', 'Google', 'Chrome', 'NativeMessagingHosts')
const MANIFEST_PATH = join(MANIFEST_DIR, `${HOST_NAME}.json`)
const RUNNER = join(HERE, 'run-host.sh')

const printOnly = process.argv.includes('--print')
const uninstall = process.argv.includes('--uninstall')

/** Extension id = first 16 bytes of sha256(public key DER), nibbles → a..p. */
function extensionId() {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'extension', 'manifest.json'), 'utf8'))
  if (typeof manifest.key !== 'string' || manifest.key === '') throw new Error('extension/manifest.json has no pinned "key"')
  const hex = createHash('sha256').update(Buffer.from(manifest.key, 'base64')).digest('hex').slice(0, 32)
  return [...hex].map((nibble) => String.fromCharCode(97 + Number.parseInt(nibble, 16))).join('')
}

if (uninstall) {
  rmSync(MANIFEST_PATH, { force: true })
  console.log(`uninstall: removed ${MANIFEST_PATH}`)
  process.exit(0)
}

const extId = extensionId()

// A wrapper script keeps Chrome's `path` a plain executable (no shell quoting
// surprises) and pins the interpreter that actually runs the host.
const runnerBody = `#!/bin/sh
# Generated by native-host/install.mjs — launches the DSH Web Companion host.
exec "${process.execPath}" "${join(HERE, 'host.mjs')}"
`
const manifest = {
  name: HOST_NAME,
  description: 'DSH Web Companion host: starts and inspects the local dsh web server',
  path: RUNNER,
  type: 'stdio',
  allowed_origins: [`chrome-extension://${extId}/`],
}

if (printOnly) {
  console.log(JSON.stringify({ manifestPath: MANIFEST_PATH, runner: RUNNER, manifest }, null, 2))
  process.exit(0)
}

mkdirSync(MANIFEST_DIR, { recursive: true })
writeFileSync(RUNNER, runnerBody)
chmodSync(RUNNER, 0o755)
writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`)
console.log(`installed: ${MANIFEST_PATH}`)
console.log(`  host name : ${HOST_NAME}`)
console.log(`  extension : chrome-extension://${extId}`)
console.log(`  runner    : ${RUNNER}`)
console.log(`  host exists: ${existsSync(join(HERE, 'host.mjs'))}`)
