#!/usr/bin/env node
/**
 * 文案单源 → 多产物（codegen）。
 *
 * 为什么要有"单源 + 生成"而不是手写两份 `messages.json`：
 * 两份手写的语言包**一定会漂移**（改了一边忘了另一边），而漂移的表现是
 * "切到中文时某几个标签还是英文"这种只有用户会看到、测试很难发现的问题。
 * 本仓在协议那边已经用过同一套办法（`protocol/messages.schema.json` → codegen → 三端产物 + `--check`），
 * 这里照搬：**一份源表 → 生成所有产物 → `--check` 做逐字节比对**。
 *
 * 输入：`extension/i18n/messages.source.json`
 *   { "<key>": { "en": "...", "zh_CN": "..." }, ... }
 *
 * 产物：
 *   1. `extension/_locales/en/messages.json`      —— Chrome 读的那份（`default_locale: "en"`）
 *   2. `extension/_locales/zh_CN/messages.json`   —— Chrome 读的那份
 *   3. `extension/src/lib/messages.generated.js`  —— 运行期兜底 + 单测可用的 JS 模块
 *
 * 用法：
 *   node extension/i18n/codegen.mjs            # 生成
 *   node extension/i18n/codegen.mjs --check    # 校验（不一致 ⇒ exit 1，用于 npm run check）
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const EXT = resolve(HERE, '..')
const SOURCE = join(HERE, 'messages.source.json')
/*
 * ★ 只**发布** en 一个语言包（用户 2026-09-13 的决定）：
 * 「用户的 chrome 设置成中文或者英文, 我们的插件都是英文版, 就可以」
 *
 * 依据：Chrome 挑语言包的规则是"按浏览器界面语言找最匹配的，找不到就退到 default_locale"。
 * 所以**只要不发布 zh_CN**，无论用户的 Chrome 是中文还是英文，插件都必然是英文版
 * —— 这正是要做成英文发行版想要的行为。（zh_CN 那一列仍留在源表里当**中文原稿/参考**，
 * 但不会再生成到 _locales/，也就永远不会被 Chrome 选中。）
 */
const SHIPPED_LOCALES = ['en']
/** 源表里必须齐的列（en 是发布语言；zh_CN 是参考稿，缺了也算源表不完整）。 */
const REQUIRED_COLUMNS = ['en', 'zh_CN']

const CHECK = process.argv.includes('--check')

const source = JSON.parse(readFileSync(SOURCE, 'utf8'))

/** 校验源表本身是否完整（缺语言、空串都算错）。 */
function validate(table) {
  const problems = []
  const keys = Object.keys(table)
  if (keys.length === 0) problems.push('源表是空的')
  for (const [key, entry] of Object.entries(table)) {
    if (!/^[A-Za-z][A-Za-z0-9_]*$/u.test(key)) problems.push(`key 不合规：${key}`)
    if (entry === null || typeof entry !== 'object') { problems.push(`${key} 不是对象`); continue }
    for (const locale of REQUIRED_COLUMNS) {
      const value = entry[locale]
      if (typeof value !== 'string' || value.trim() === '') problems.push(`${key} 缺 ${locale} 文案`)
    }
    for (const extra of Object.keys(entry)) {
      if (!REQUIRED_COLUMNS.includes(extra)) problems.push(`${key} 有未知语言：${extra}`)
    }
  }
  return problems
}

const problems = validate(source)
if (problems.length > 0) {
  console.error('✗ 文案源表有问题：')
  for (const p of problems) console.error(`   · ${p}`)
  process.exit(1)
}

/** Chrome 的 messages.json 形状。 */
function chromeMessages(locale) {
  const out = {}
  for (const [key, entry] of Object.entries(source)) out[key] = { message: entry[locale] }
  return `${JSON.stringify(out, null, 2)}\n`
}

/** 给运行期/单测用的 JS 模块（JSON import assertions 在各处不统一，直接生成 JS 最稳）。 */
function jsModule() {
  const lines = [
    '/*',
    ' * AUTO-GENERATED by extension/i18n/codegen.mjs — 不要手改。',
    ' * 源表：extension/i18n/messages.source.json',
    ' * 重新生成：node extension/i18n/codegen.mjs',
    ' */',
    '',
    '/** 默认语言。manifest 的 default_locale 必须与它一致。 */',
    "export const DEFAULT_LOCALE = 'en'",
    '',
    '/** 全部语言包（key → 文案）。 */',
    'export const MESSAGES = {',
  ]
  for (const locale of SHIPPED_LOCALES) {
    lines.push(`  ${JSON.stringify(locale)}: {`)
    for (const [key, entry] of Object.entries(source)) {
      lines.push(`    ${JSON.stringify(key)}: ${JSON.stringify(entry[locale])},`)
    }
    lines.push('  },')
  }
  lines.push('}', '')
  return lines.join('\n')
}

const targets = [
  ...SHIPPED_LOCALES.map((locale) => ({ path: join(EXT, '_locales', locale, 'messages.json'), body: chromeMessages(locale) })),
  { path: join(EXT, 'src', 'lib', 'messages.generated.js'), body: jsModule() },
]

if (CHECK) {
  let stale = 0
  for (const t of targets) {
    if (!existsSync(t.path)) {
      console.error(`✗ 产物不存在：${t.path}`)
      stale += 1
      continue
    }
    if (readFileSync(t.path, 'utf8') !== t.body) {
      console.error(`✗ 产物已过期：${t.path}`)
      stale += 1
    }
  }
  if (stale > 0) {
    console.error('  → 跑 `node extension/i18n/codegen.mjs` 重新生成')
    process.exit(1)
  }
  console.log(`i18n: OK（${String(Object.keys(source).length)} 条文案；发布语言 ${SHIPPED_LOCALES.join('/')} = ${String(targets.length)} 个产物逐字节一致）`)
  process.exit(0)
}

for (const t of targets) {
  mkdirSync(dirname(t.path), { recursive: true })
  writeFileSync(t.path, t.body)
}
console.log(`i18n: 已生成 ${String(targets.length)} 个产物（${String(Object.keys(source).length)} 条文案；只发布 ${SHIPPED_LOCALES.join(' / ')}）`)
for (const t of targets) console.log(`  ${t.path.replace(`${EXT}/`, '')}`)
