#!/usr/bin/env node
/**
 * Provision the extension <-> bridge-plugin pairing.
 *
 *   1. Generate (once) an RSA key pair and pin the extension id by writing the
 *      public key into `extension/manifest.json` — an unpacked extension's id is
 *      otherwise derived from its directory path, which changes per checkout.
 *   2. Generate the shared key and write `$DSH_HOME/dsh-web-companion.json`
 *      (0600) with the trusted extension origin list.
 *   3. Write the same key + port into `extension/src/lib/dev-config.js` so the
 *      development build can talk to the bridge without an options page.
 *
 * Usage:
 *   node scripts/init-key.mjs [--home <dsh home>] [--port 3080] [--print-id]
 */
import { createHash, generateKeyPairSync, randomBytes } from 'node:crypto'
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const EXT_DIR = join(ROOT, 'extension')
const KEY_FILE = join(ROOT, 'scripts', '.dev-extension-key.json')

const argOf = (name, fallback) => {
  const at = process.argv.indexOf(`--${name}`)
  return at === -1 ? fallback : process.argv[at + 1]
}
const hasFlag = (name) => process.argv.includes(`--${name}`)

const dshHome = resolve(argOf('home', process.env.DSH_HOME?.trim() || join(homedir(), '.dsh')))
const port = Number(argOf('port', '3080'))

/** Chrome extension id from a DER public key: sha256, first 16 bytes, nibble -> a..p. */
function extensionIdFromPublicKey(der) {
  const hex = createHash('sha256').update(der).digest('hex').slice(0, 32)
  return [...hex].map((nibble) => String.fromCharCode(97 + Number.parseInt(nibble, 16))).join('')
}

/** Reuse the pinned key pair, or create one on first run. */
function loadOrCreateKeyPair() {
  if (existsSync(KEY_FILE)) {
    const stored = JSON.parse(readFileSync(KEY_FILE, 'utf8'))
    const der = Buffer.from(stored.publicKeyDer, 'base64')
    return { der, privateKeyPem: stored.privateKeyPem, created: false }
  }
  const { publicKey, privateKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'der' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  })
  const stored = { publicKeyDer: Buffer.from(publicKey).toString('base64'), privateKeyPem: privateKey }
  writeFileSync(KEY_FILE, `${JSON.stringify(stored, null, 2)}\n`, { mode: 0o600 })
  return { der: Buffer.from(publicKey), privateKeyPem: privateKey, created: true }
}

const { der, created } = loadOrCreateKeyPair()
const extensionId = extensionIdFromPublicKey(der)
const manifestKey = der.toString('base64')

// 1. pin the extension id in the manifest
const manifestPath = join(EXT_DIR, 'manifest.json')
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
manifest.key = manifestKey
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`)

// 2. pairing file for the bridge plugin — reuse the existing key unless
//    --rotate is passed, so re-provisioning a different port never silently
//    invalidates a running DSH instance or an already-loaded extension.
const COMPANION_FILE = 'dsh-web-companion.json'
const companionPathEarly = join(dshHome, COMPANION_FILE)
const existingKey = (() => {
  try { return JSON.parse(readFileSync(companionPathEarly, 'utf8')).key } catch { return undefined }
})()
const bridgeKey = (hasFlag('rotate') || typeof existingKey !== 'string' || existingKey === '')
  ? randomBytes(32).toString('base64').replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/u, '')
  : existingKey
const companion = {
  version: 1,
  key: bridgeKey,
  extensionOrigins: [`chrome-extension://${extensionId}`],
  port,
  createdAt: new Date().toISOString(),
}
mkdirSync(dshHome, { recursive: true })
const companionPath = join(dshHome, COMPANION_FILE)
writeFileSync(companionPath, `${JSON.stringify(companion, null, 2)}\n`, { mode: 0o600 })
chmodSync(companionPath, 0o600)

// 3. dev config inside the extension
writeFileSync(
  join(EXT_DIR, 'src', 'lib', 'dev-config.js'),
  `/**\n * AUTO-GENERATED by scripts/init-key.mjs — do not edit by hand.\n */\nexport const DEV_CONFIG = { port: ${String(port)}, key: '${bridgeKey}' }\n`,
)

console.log(JSON.stringify({
  extensionId,
  extensionKeyPinned: created ? 'generated' : 'reused',
  pairingFile: companionPath,
  port,
  origin: `chrome-extension://${extensionId}`,
}, null, 2))
